# Generated by Django 4.2.11 on 2025-02-15 20:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCuadricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to=core.models.image_upload_path)),
                ('descripcion', models.TextField()),
                ('seccion', models.CharField(choices=[('fundacion', 'Fundación'), ('instituto', 'Instituto'), ('lutheria', 'Luthería')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Boton',
        ),
    ]
