# Generated by Django 4.2.11 on 2025-03-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itemcuadricula_delete_boton'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcuadricula',
            name='resumen',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
